server:
  port: 8080

spring:
  application:
    name: jobspoon

  datasource:
    url: jdbc:mysql://${SPRING_DATABASE_HOST:localhost}:3306/${SPRING_DATABASE_NAME:aim_db}
    username: ${SPRING_DATABASE_USER:eddi}
    password: ${SPRING_DATABASE_PASSWORD:eddi@123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:eddi@123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

kakao:
  login-url: ${KAKAO_LOGIN_URL:https://kauth.kakao.com/oauth/authorize}
  client-id: ${KAKAO_CLIENT_ID:your-local-client-id}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:5173/auth/kakao/callback}
  token-request-uri: ${KAKAO_TOKEN_REQUEST_URI:https://kauth.kakao.com/oauth/token}
  user-info-request-uri: ${KAKAO_USER_INFO_REQUEST_URI:https://kapi.kakao.com/v2/user/me}

#kakao:
#  login-url: ${KAKAO_LOGIN_URL}
#  client-id: ${KAKAO_CLIENT_ID}
#  redirect-uri: ${KAKAO_REDIRECT_URI}
#  token-request-uri: ${KAKAO_TOKEN_REQUEST_URI}
#  user-info-request-uri: ${KAKAO_USER_INFO_REQUEST_URI}

cors:
  allow:
    origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000}

#cors:
#  allow:
#    origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    org.springframework: INFO
